### ISSUE TITLE
Accessing handler config object

### ISSUE THREAD

**Issue by rossgeesman** [PagerDuty/lita-github#35]
Hi, I was referencing this project in building my own Lita bot and I'm curious how you have access to Lita's config object as you appear to here:

```
/lib/lita-github/config.rb

def config
      Lita.config.handlers.github
end
```
It's my understanding (and experience in my own project) that Lita's  handler config object needs a corresponding `config :symbol` in the handler's class or raises an error. How did you get around that? I'm somewhat new to Ruby, sorry if the question is super obvious :) Any help you can provide will be much appreciated.

**Comment by theckman** [comment]
It's a helper that Lita provides, I don't remember doing any magic to get this. It works with both adapters and handlers based on what you provide after `config`.

**Comment by theckman** [comment]
To add on, as I remember it... the `config` method you have available within your handler is just an alias to `Lita.config.handler.<handler_name>`.

**Comment by theckman** [comment]
@rossgeesman I'm going to close this issue. Let me know if you have any further questions. :)
